export const TEXT_MESSAGE = 'TEXT_MESSAGE';
export const CHANGE_NICKNAME = 'CHANGE_NICKNAME';
export const DELETE_LAST_MESSAGE = 'DELETE_LAST_MESSAGE';
export const FADE_LAST = 'FADE_LAST';
export const USER_TYPING = 'USER_TYPING';